png("plot3.png",width=480,height=480)
powerconsumption<-read.csv2(file="household_power_consumption.txt",header=FALSE,skip=66637,nrows=2880,stringsAsFactors=FALSE)
names(powerconsumption)<-c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
powerconsumption$datetime<-paste(powerconsumption$Date,powerconsumption$Time)
s<-strptime(powerconsumption$date,format='%d/%m/%Y %H:%M:%S')
plot(s,powerconsumption$Sub_metering_1,xlab="",ylab="Energy sub metering",type="l")
lines(s,powerconsumption$Sub_metering_2,col="red")
lines(s,powerconsumption$Sub_metering_3,col="blue")
legend("topright",col=c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1)
dev.off()